name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Set up Gradle 8.14
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.14'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest --stacktrace

    - name: Build debug APK
      run: ./gradlew assembleDebug --parallel

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
        if-no-files-found: error

    - name: Create release summary
      if: success()
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "✅ Build completed: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "📱 Debug APK uploaded: debug-apk" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Download APK" >> $GITHUB_STEP_SUMMARY
        echo "Download the debug APK from the 'Actions' tab under 'Artifacts'." >> $GITHUB_STEP_SUMMARY
