# .github/workflows/android.yml

name: Android CI Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Use the exact Gradle version from your project
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.14' 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Using --no-configuration-cache for better stability in CI environments
      - name: Run Android Lint
        run: ./gradlew lintDebug --no-configuration-cache

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-configuration-cache

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          # Path to the generated APK. Your module is 'app', so this is correct.
          path: app/build/outputs/apk/debug/app-debug.apk